# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04  # Change this if using a different OS version
  tools:
    python: "3.9"   # Specify the Python version compatible with your dependencies

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

python:
  install:
    - requirements: requirements.txt
